language: python
python:
  - 3.8.5
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python3 -m pytest

notifications:
  email:
    reciplients:
      - toxxa099@gmail.com
    on_success: never
    on_failure: always