language: python
python:
  - 3.8.5
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script:
  - python3 -m pytest --cov=src/

notifications:
  email:
    reciplients:
      - toxxa099@gmail.com
    on_success: never
    on_failure: always

after_success:
  - name: Send coverage to Coveralls
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run: coveralls --service=github